### PR TITLE
Rework

### PR DESCRIPTION
**Pull request by shadowspawn**
# Pull Request

Try a new terminology, reword, and expand examples of alternative approaches.

Making a PR to you! Feel free to comment here so you comment on specific lines, or in your PR going the other way. 😄

### CODE REVIEW

**Comment by shadowspawn** [comment]
Worked through entire doc. I left out variadic example as I didn't think it added enough (although I liked the example scenario), but I added a comment at top that using 0-1 arguments in examples.

 I have wondered about showing how to specify an option-argument starting with a `-` (or potential parsing surprise), but it wasn't part of my main goals for this story so left out.

**Comment by shadowspawn** [comment]
I was working on wrong branch in my fork (oops), so all the subsequent changes have arrived here in one commit when I copied content, and GitHub is not tracking the file rename so showing new files and old file and not a diff as such.

**Comment by shadowspawn** [comment]
Any comments @heyjiawei ?

I have been thinking about these issue most of this year, so apologies that lots of changes to what you wrote! But your start got this underway, and got me rethinking the terminology as you asked questions and I tried to answer.

**Comment by heyjiawei** [comment]
Hello hello @shadowspawn I have read the changes and I like how neat it is! I have no issues with the changes, just wondering if we should mention https://github.com/tj/commander.js/pull/1332#discussion_r476330646
>Commander follows the GNU convention and allows options before or after the operands. So by putting the options last, the option values do not get confused with the operands.

**Comment by shadowspawn** [comment]
That is mentioned in "Alternative: Put options last"

**Comment by heyjiawei** [comment]
oh yes. Alright looks good to me

**Pull request merged**
